### ISSUE TITLE
Homepage and navigation

### ISSUE THREAD

**Issue by j4-m** [localgovdrupal/localgov_demo#11]
Could we include a homepage and main navigation? I feel this would give users of the demo a much better understanding of how the features hang together.

**Comment by andybroomfield** [comment]
Realted is is generating the services menu which is used on BHCC (Possible also Croydon)
https://github.com/localgovdrupal/localgov_services/issues/82
and PRs
https://github.com/localgovdrupal/localgov_services/pull/83
https://github.com/localgovdrupal/localgov_services/pull/84

**Comment by msayoung** [comment]
We did this. closing.
