### ISSUE TITLE
Replace campaigns content with subsites

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_demo#12]
Trying to install localgov_demo and greeted by
`Unable to install modules: module 'localgov_demo' is missing its dependency module localgov_campaigns.`

This is due to the replacement of campaigns with subsites, so the content should also be updated and the dependency replaced.

**Comment by mattrfletcher** [comment]
@andybroomfield @finnlewis Is this as simple as changing the list of dependencies in localgov_demo.info.yml from - localgov_campaigns:localgov_campaigns to - localgov_subsites:localgov_subsites or is there something else that needs to be done.

**Comment by tebb** [comment]
Matt.  This isn't labelled "good first issue".  Might be best to stick to those for a while?

I think the answer to your question is:  "the content should also be updated" and I don't know how involved that is.

**Comment by andybroomfield** [comment]
@mattrfletcher The demo content is in seralized json files under the /content folder. I think it needs someone to move the content over and regenerate as trying to do that in code may be difficult. @finnlewis will be able to confirm the module and process to generate them.

**Comment by danchamp** [comment]
It turns out there is no demo campaign content actually defined in the module, and localgov_campaigns is just declared as a dependency.

I'll pick this up just now.
