### ISSUE TITLE
Fix 2 docs links on demo site

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_demo#132]
On https://demo.localgovdrupal.org/localgov-drupal-demo the following links should point to https://docs.localgovdrupal.org/

- "Read the docs" button beneath the lake image
- "Go to the documentation" bottom left of page

**Comment by willguv** [comment]
@markconroy could you have a quick look at this please? Many thanks!

**Comment by markconroy** [comment]
@willguv https://github.com/localgovdrupal/localgov_demo/pull/133
