### ISSUE TITLE
Add localgov modules to composer.json

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_demo#15]
When #13 merges that will add localgov_subsites as a dependancy.
Looking at the composer.json, there are no localgov modules listed there. Should those be added?

**Comment by ekes** [comment]
Should we just make it depend on the profile? It's a demo of the profile, which as just extra code you don't use you might not want on production actually, but you don't get a demo of the profile without the profile?

**Comment by keelanfh** [comment]
Done in #89
