### ISSUE TITLE
Write tests for content from localgov_demo module ahead of upgrade testing

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_demo#24]
From localgovdrupal/localgov#181 

Write tests for the localgov_demo module (Estimate: 13)

Write browser tests to test that the expected content is present and displayed.
Starting this in the D8 branch as tests should be D8/D9 independent.
One test for each type of content = ~ 10 (+ events + news).

- [x] Write test for **service landing page** content in localgov_demo module
- [x] Write test for **service sub-landing page** page content in localgov_demo module 
- [x] Write test for **service page** content in localgov_demo module 
- [x] Write test for **step-by-step overview page** content in localgov_demo module 
- [x] Write test for **step-by-step page** content in localgov_demo module 
- [x] Write test for **guide overview page** content in localgov_demo module 
- [x] Write test for **guide page** content in localgov_demo module 
- [x] Write test for **event page** content in localgov_demo module

**Comment by finnlewis** [comment]
Passing this to @stephen-cox to srite a couple of tests, then @ekes  and @msayoung for further tests.

**Comment by stephen-cox** [comment]
@finnlewis @ekes @msayoung I have added content tests for service landing pages and sub-landing. I've also added some guidelines for writing content tests to the [README](https://github.com/localgovdrupal/localgov_demo/tree/feature/24-content-tests#writing-tests).

It would be good to get some other eyes on this to agree we're happy with this direction for testing content.

**Comment by stephen-cox** [comment]
@finnlewis @msayoung This was moved to done, but there's no PR for it.

Looks like all the content is in the [feature/24-content-tests ](https://github.com/localgovdrupal/localgov_demo/tree/feature/24-content-tests) branch

**Comment by finnlewis** [comment]
I think we could call this done if the test are written and pass locally, but they fail on Github CI.

Maybe we should check the tests do pass locally first, as perhaps there was another issue with the demo content module that caused issues.

**Comment by finnlewis** [comment]
OK - just tested locally and all the tests pass.

```
$ lando phpunit web/modules/contrib/localgov_demo/
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Testing /app/web/modules/contrib/localgov_demo
Content (Drupal\Tests\localgov_demo\Functional\Content)
 ✔ Page content

Time: 02:18.326, Memory: 14.00 MB

OK (1 test, 86 assertions)

**Comment by msayoung** [comment]
blocked due to https://github.com/localgovdrupal/localgov/issues/253
