### ISSUE TITLE
Add default content to localgov_demo for all content types that ship with LocalGov Drupal

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_demo#25]
Hi @willguv 

We never did get around to adding more content to the localgov_demo module. We should add reasonable content for subsites, news, events alerts etc. to cover all the types of content that could be created with a defaul installation.

This will be needed for the updgrade tests that we are talking about in #24 but also for a better public demo for anyone who wants to take it for a spin locally, and for a demo site that could re-install itself regularly.

So the question returns, should we: 

1. use (almost?) real content from an existing council site (Croydon? Lambeth?) 
2. write content that is clearly not from a real council
3. use lorem ipsum of some sort.

Once decided, this could become a team activity on the dev site early this sprint to get everyone managing content to get more familiar with the system and start to build awareness of its features. 

Any thoughts @ekes @andybroomfield @msayoung @markconroy @stephen-cox @Adnan-cds ?

**Comment by willguv** [comment]
Thanks for raising this @finnlewis. I’m in favour of 1) as there’s lots of real examples from Croydon, Lambeth, Brighton and elsewhere that can have names and contact details removed. We need to pick the best and upload them.

I also need to write two blog posts, start a new procurement, continue drafting product pages for shop ldg.org and support writing acceptance tests for sprint 2 - so there’s a lot on my plate this sprint. (Need cards on Github or Trello for these)

Would be good to share this particular job out.

**Comment by markconroy** [comment]
I think this sounds like a great idea. 

I tried to install the demo_content module, but it only installed about 8 nodes for me. would be great to have it more fully fleshed out.

My preference would be to not use Lorem Ipsum (besides perhaps for body text).

**Comment by finnlewis** [comment]
Will suggests that Ben Hills-Jones can help with this, finding good examples of content.

**Comment by msayoung** [comment]
Yep, I'm up for being involved. I like real generalised content , maybe from an obviously imaginary council. 

From recent experience I do recommend making a brief plan for creating it - otherwise we'll be forever reviewing it.

**Comment by willguv** [comment]
We've previously identified examples of each content format

https://docs.google.com/spreadsheets/d/1LKlMG_YUp1UjEv9hKpuTN8K79gCmQ5erj47zfHRbKGY/edit?usp=drive_open&ouid=106883542178247724730

There will be some OK examples here, but there might be better ones

**Comment by stephen-cox** [comment]
I have re-installed the LocalGov UAT site so we can start adding content to https://localgovdrupal.agile.coop/

There are 3 accounts; an admin account, a content designer and a content author. User names are:

- LocalGov Admin
- LocalGov Content designer
- LocalGov Author

Passwords for these accounts are in Slack #technical-group channel.

**Comment by finnlewis** [comment]
Nice one @stephen-cox !

@msayoung and I have started a spreadsheet of content planning to help make sure we create a decent spread of content. 

https://docs.google.com/spreadsheets/d/1hsFBnvrBl0juqVA_bRA3Yz1vlNay1epxjW1Y72lLlUE/edit#gid=1154462836

We will be meeting next week to do some mob content writing, in case anyone else wants to join!

Content addition for Localgov Demo module (LocalGov Drupal Beta)
Wednesday, 5 May · 14:00 – 14:50
Google Meet joining info
Video call link: https://meet.google.com/usa-dsnu-cif
Or dial: ‪(GB) +44 20 3956 8180‬ PIN: ‪321 990 143‬#
More phone numbers: https://tel.meet/usa-dsnu-cif?pin=3890923792595

**Comment by finnlewis** [comment]
Maria has been leading the charge to create a spread of content on https://localgovdrupal.agile.coop/ with help from me, @richard-s-rowley @AlexandraClark83 @willguv and @benhillsjones (thanks all).

We've since been building the default content on this branch https://github.com/localgovdrupal/localgov_demo/commits/feature/25-default-content-update

I'm hoping to get this to a state to be tested and merged by the end of the sprint.
