### ISSUE TITLE
Internal references in link fields broken 

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_demo#36]

**Comment by msayoung** [comment]
eg **Sports and physical activity** sub-landing page should link to **A to Z of sports and activities**
 in the Links field (localgov_topics) - this is a link field rather than an entity reference field.

note the internal links on the AtoZ are working - so this issues isn't universal (i assume to do with the order they are created)

another example:
Births, deaths, marriages and citizenship should link to Marriage and civil partnerships which should link to Get married or form a civil partnership: step by step 

none of these links appear when we enable the demo content module

**Comment by finnlewis** [comment]
Thanks @msayoung ! I will see what I can do.
