### ISSUE TITLE
Update content for the localgov_demo module

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_demo#48]
We had a content creationg session this morning and updated content on https://demo.localgovdrupal.org/

Now need to wrap it up into localgov_demo.

See 

 - https://github.com/localgovdrupal/localgov/issues/314
 - https://github.com/localgovdrupal/localgov_subsites/issues/50

**Comment by msayoung** [comment]
I think we can close this one now @finnlewis ?
