### ISSUE TITLE
Missing news room title on homepage

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_demo#61]
After doing a fresh install the News Room content type link is missing a title.

![Screenshot 2021-10-05 at 14-44-02 Localgov Drupal Demo Drush Site-Install](https://user-images.githubusercontent.com/7189914/136035274-442207d2-1a5e-4ccf-95b8-2ee7fb47d5a9.png)

**Comment by finnlewis** [comment]
Thanks @stephen-cox  - I was just about to post the same. 
Odd!

**Comment by msayoung** [comment]
i'm not seeing this anymore, so closing
