### ISSUE TITLE
Call to deprecated function drupal_get_path():    

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_demo#68]
When running tests on https://github.com/localgovdrupal/localgov_geo/runs/4507201665?check_suite_focus=true we are seeing a numebr of new code deprecation errors.

 ------ -------------------------------------------------------------------- 
  Line   modules/contrib/localgov_demo/localgov_demo.module                  
 ------ -------------------------------------------------------------------- 
  44     Call to deprecated function drupal_get_path():                      
         in drupal:9.3.0 and is removed from drupal:10.0.0. Use              
           \Drupal\Core\Extension\ExtensionPathResolver::getPath() instead.  
 ------ --------------------------------------------------------------------

**Comment by keelanfh** [comment]
Closed by #69

**Comment by keelanfh** [comment]
Closed by #69
