### ISSUE TITLE
Update demo content to account for upgrade to leaflet 2.1.20

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_demo#73]
See https://github.com/localgovdrupal/localgov_geo/issues/48#issuecomment-1036149762

**Comment by stephen-cox** [comment]
@andybroomfield @ekes There doesn't appear to be any issues with the default content in the Demo module once the Drupal Leaflet module is upgraded to 2.2. PR for this is here: https://github.com/localgovdrupal/localgov_geo/pull/59

Can one of you confirm this?

**Comment by andybroomfield** [comment]
Running `lando drush si localgov -y; lando drush en localgov_demo -y` installs fine.
But wasn't it the tests that failed?

**Comment by finnlewis** [comment]
@andybroomfield is this good to close?
